---
- host: all
  become: True
  tasks:
  - name: install python pip
    yum:
      name: python-pip
      state: present
  - name: install docker
    yum:
      name: docker
      state: present
  - name: start docker 
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes 
  - name: install docker-py python module
    pip:
      name: docker-py
      state: present
  - name: start the container
    community.docker.docker_container:
      name: thangapp
      image: "thangsu/thangapp:${{DOCKER_TAG}}"
      state: started
      published_ports:
        - 0.0.0.0:8080:8080

  